export const DEFAULT_HOMEPAGE_SECTION_TEMPLATES = [
  {
    id: 'template_hero',
    sectionType: 'hero_banner',
    title: 'Hero',
    subtitle: 'Primary visual banner for this locality',
    status: 'active',
    visible: true,
    sortOrder: 10,
    ctaLabel: 'Explore Businesses',
    ctaType: 'search_category',
    ctaTarget: 'all',
    showViewAll: false
  },
  {
    id: 'template_search',
    sectionType: 'search_discovery',
    title: 'Search & Discover',
    subtitle: 'Locality-aware search with quick categories',
    status: 'active',
    visible: true,
    sortOrder: 20,
    showViewAll: false
  },
  {
    id: 'template_emergency',
    sectionType: 'emergency_grid',
    title: 'Emergency Services',
    subtitle: 'Critical support nearby',
    status: 'active',
    visible: true,
    sortOrder: 30,
    categoryIds: ['health-medical', 'home-services', 'automotive'],
    maxItems: 8,
    visibleSlots: 8,
    showViewAll: true
  },
  {
    id: 'template_promo',
    sectionType: 'promo_banner',
    title: 'Promoted This Week',
    subtitle: 'Scheduled paid banner placement',
    status: 'active',
    visible: true,
    sortOrder: 40,
    placementKey: 'homepage_inline_primary',
    showViewAll: false
  },
  {
    id: 'template_featured',
    sectionType: 'featured_businesses',
    title: 'Premium Featured Businesses',
    subtitle: 'Priority merchants in this locality',
    status: 'active',
    visible: true,
    sortOrder: 50,
    maxItems: 6,
    visibleSlots: 3,
    desktopCardCount: 3,
    mobileCardCount: 2,
    mobileDisplayMode: 'carousel',
    autoRotate: true,
    showViewAll: true
  },
  {
    id: 'template_food_shelf',
    sectionType: 'business_shelf',
    title: 'Home Kitchens & Bakers',
    subtitle: 'Curated shelf with repeatable category merchandising',
    status: 'active',
    visible: true,
    sortOrder: 60,
    categoryId: 'food-restaurants',
    maxItems: 6,
    visibleSlots: 4,
    desktopCardCount: 4,
    mobileCardCount: 2,
    mobileDisplayMode: 'carousel',
    autoRotate: true,
    showViewAll: true
  },
  {
    id: 'template_health_shelf',
    sectionType: 'business_shelf',
    title: 'Doctors & Clinics',
    subtitle: 'Verified health and care businesses in this locality',
    status: 'active',
    visible: true,
    sortOrder: 62,
    categoryId: 'health-medical',
    maxItems: 6,
    visibleSlots: 4,
    desktopCardCount: 4,
    mobileCardCount: 2,
    mobileDisplayMode: 'stack',
    autoRotate: true,
    showViewAll: true
  },
  {
    id: 'template_home_shelf',
    sectionType: 'business_shelf',
    title: 'Home Services Near You',
    subtitle: 'Quick access to trusted electricians, plumbers, and repair pros',
    status: 'active',
    visible: true,
    sortOrder: 64,
    categoryId: 'home-services',
    maxItems: 6,
    visibleSlots: 4,
    desktopCardCount: 4,
    mobileCardCount: 2,
    mobileDisplayMode: 'carousel',
    autoRotate: true,
    showViewAll: true
  },
  {
    id: 'template_beauty_shelf',
    sectionType: 'business_shelf',
    title: 'Beauty & Wellness Picks',
    subtitle: 'Salons, skin care, and grooming experts around you',
    status: 'active',
    visible: true,
    sortOrder: 66,
    categoryId: 'beauty-wellness',
    maxItems: 6,
    visibleSlots: 4,
    desktopCardCount: 4,
    mobileCardCount: 2,
    mobileDisplayMode: 'carousel',
    autoRotate: true,
    showViewAll: true
  },
  {
    id: 'template_retail_shelf',
    sectionType: 'business_shelf',
    title: 'Groceries & Daily Needs',
    subtitle: 'Everyday essentials from trusted nearby stores',
    status: 'active',
    visible: true,
    sortOrder: 67,
    categoryId: 'shopping-retail',
    maxItems: 6,
    visibleSlots: 4,
    desktopCardCount: 4,
    mobileCardCount: 2,
    mobileDisplayMode: 'carousel',
    autoRotate: true,
    showViewAll: true
  },
  {
    id: 'template_domestic_strip',
    sectionType: 'text_business_strip',
    title: 'Maid & Domestic Help',
    subtitle: 'Trusted daily support professionals nearby',
    status: 'active',
    visible: true,
    sortOrder: 65,
    categoryId: 'home-services',
    maxItems: 4,
    visibleSlots: 4,
    desktopCardCount: 4,
    mobileCardCount: 2,
    mobileDisplayMode: 'stack',
    showViewAll: true
  },
  {
    id: 'template_care_strip',
    sectionType: 'text_business_strip',
    title: 'Clinic & Care Experts',
    subtitle: 'Text-first local listings for quick comparison',
    status: 'active',
    visible: true,
    sortOrder: 68,
    categoryId: 'health-medical',
    maxItems: 4,
    visibleSlots: 4,
    desktopCardCount: 4,
    mobileCardCount: 2,
    mobileDisplayMode: 'stack',
    showViewAll: true
  },
  {
    id: 'template_education_strip',
    sectionType: 'text_business_strip',
    title: 'Tutors & Training Experts',
    subtitle: 'Quick-compare local education and coaching listings',
    status: 'active',
    visible: true,
    sortOrder: 69,
    categoryId: 'education-training',
    maxItems: 4,
    visibleSlots: 4,
    desktopCardCount: 4,
    mobileCardCount: 2,
    mobileDisplayMode: 'stack',
    showViewAll: true
  },
  {
    id: 'template_categories',
    sectionType: 'category_grid',
    title: 'Explore by Categories',
    subtitle: 'Jump into high-intent categories',
    status: 'active',
    visible: true,
    sortOrder: 70,
    categoryIds: ['food-restaurants', 'health-medical', 'beauty-wellness', 'home-services', 'shopping-retail', 'education-training', 'professional-services', 'automotive'],
    maxItems: 12,
    visibleSlots: 12,
    showViewAll: true
  },
  {
    id: 'template_offers',
    sectionType: 'offers_list',
    title: 'Offers & Deals',
    subtitle: 'Scheduled offers filtered by locality and pincode',
    status: 'active',
    visible: true,
    sortOrder: 80,
    maxItems: 4,
    showViewAll: true
  },
  {
    id: 'template_updates',
    sectionType: 'updates_feed',
    title: 'Locality Updates',
    subtitle: 'Timed announcements and community updates',
    status: 'active',
    visible: true,
    sortOrder: 90,
    maxItems: 4,
    showViewAll: true
  },
  {
    id: 'template_verified',
    sectionType: 'verified_business_grid',
    title: 'Verified Businesses Near You',
    subtitle: 'Trusted approved listings for this locality',
    status: 'active',
    visible: true,
    sortOrder: 100,
    maxItems: 9,
    visibleSlots: 5,
    desktopCardCount: 5,
    mobileCardCount: 2,
    mobileDisplayMode: 'stack',
    autoRotate: true,
    showViewAll: true
  },
  {
    id: 'template_trust',
    sectionType: 'trust_strip',
    title: 'Trust Highlights',
    subtitle: 'Closing reassurance and platform trust points',
    status: 'active',
    visible: true,
    sortOrder: 110,
    showViewAll: false
  }
];

export const DEFAULT_FALLBACK_LISTING_AD_TEMPLATES = [
  {
    id: 'fallback_ad_growth',
    title: 'Grow Your Business with Localisy',
    description: 'Reach local customers every month.',
    badge: 'Advertisement',
    ctaText: 'Advertise Now',
    backgroundColor: '#ede9fe',
    imageUrl: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=640&q=80',
    actionType: 'lead_form',
    tags: ['business', 'advertise', 'marketing'],
    placementKey: 'homepage_sidebar_top',
    deviceTarget: 'all',
    mobileRowPosition: 3
  },
  {
    id: 'fallback_ad_food',
    title: 'Delicious food delivered fast!',
    description: 'Up to 50% OFF on your first order.',
    badge: 'Advertisement',
    ctaText: 'Order Now',
    backgroundColor: '#064e3b',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=640&q=80',
    actionType: 'landing_page',
    targetCategoryId: 'food-restaurants',
    categoryIds: ['food-restaurants'],
    tags: ['food', 'restaurant', 'delivery'],
    placementKey: 'homepage_sidebar_food',
    deviceTarget: 'all',
    mobileRowPosition: 3
  },
  {
    id: 'fallback_ad_clinic',
    title: 'Radiance Skin & Hair Clinic',
    description: '20% OFF on all services.',
    badge: 'Advertisement',
    ctaText: 'Book Now',
    backgroundColor: '#fce7f3',
    imageUrl: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=640&q=80',
    actionType: 'landing_page',
    targetCategoryId: 'beauty-wellness',
    categoryIds: ['beauty-wellness', 'health-medical'],
    tags: ['clinic', 'beauty', 'salon', 'skin'],
    placementKey: 'homepage_sidebar_clinic',
    deviceTarget: 'all',
    mobileRowPosition: 3
  },
  {
    id: 'fallback_ad_marketing',
    title: 'Digital Marketing That Gets You More Customers',
    description: 'SEO, social media and ads for local businesses.',
    badge: 'Advertisement',
    ctaText: 'Get Free Audit',
    backgroundColor: '#eef2ff',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=640&q=80',
    actionType: 'lead_form',
    categoryIds: ['professional-services', 'digital-technology'],
    tags: ['marketing', 'seo', 'social media'],
    placementKey: 'homepage_sidebar_marketing',
    deviceTarget: 'all',
    mobileRowPosition: 3
  }
];

export const DEFAULT_HERO_STAT_TEMPLATES = [
  {
    enabled: true,
    label: 'Happy Users',
    value: '15K+',
  },
  {
    enabled: true,
    label: 'Verified Businesses',
    value: '3K+',
  },
  {
    enabled: true,
    label: 'Average Rating',
    value: '4.8',
  },
];

export const DEFAULT_HERO_BANNER_DRAFT_DEFAULTS = {
  ctaLabel: 'Explore Businesses',
  ctaType: 'search_category',
  ctaTarget: 'all',
  durationDays: 30,
};

export const DEFAULT_HERO_QUICK_ACTIONS = [
  {
    label: 'Restaurants',
    categoryId: 'food-restaurants',
    subcategoryId: 'restaurants',
  },
  {
    label: 'Doctors',
    categoryId: 'health-medical',
    subcategoryId: 'clinics',
  },
  {
    label: 'Electricians',
    categoryId: 'home-services',
    subcategoryId: 'electricians',
  },
  {
    label: 'Home Bakers',
    categoryId: 'food-restaurants',
    subcategoryId: 'bakeries',
  },
  {
    label: 'Plumbers',
    categoryId: 'home-services',
    subcategoryId: 'plumbers',
  },
  {
    label: 'Maid Services',
    categoryId: 'home-services',
    subcategoryId: 'house-cleaning',
  },
];

export const DEFAULT_SEARCH_SHORTCUT_CATEGORY_IDS = [
  'food-restaurants',
  'health-medical',
  'home-services',
  'beauty-wellness',
  'shopping-retail',
  'professional-services',
];
