import { 
  Locality, Category, Business, StateMaster, CityMaster, AreaMaster, CommunityItem, CRMContact, MarketingCoupon 
} from './types';

// Master data for Locations
export const MASTER_STATES: StateMaster[] = [
  { id: 'mh', name: 'Maharashtra' },
  { id: 'ka', name: 'Karnataka' },
  { id: 'dl', name: 'Delhi' }
];

export const MASTER_CITIES: CityMaster[] = [
  // Maharashtra
  { id: 'mumbai', stateId: 'mh', name: 'Mumbai' },
  { id: 'pune', stateId: 'mh', name: 'Pune' },
  // Karnataka
  { id: 'bengaluru', stateId: 'ka', name: 'Bengaluru' },
  // Delhi
  { id: 'delhi', stateId: 'dl', name: 'New Delhi' }
];

export const MASTER_AREAS: AreaMaster[] = [
  // Mumbai (Bandra West domain area hub)
  { id: 'bandra-w', cityId: 'mumbai', name: 'Bandra West', pincode: '400050' },
  { id: 'bandra-e', cityId: 'mumbai', name: 'Bandra East', pincode: '400051' },
  { id: 'juhu', cityId: 'mumbai', name: 'Juhu', pincode: '400049' },
  { id: 'khar-w', cityId: 'mumbai', name: 'Khar West', pincode: '400052' },
  { id: 'santacruz-w', cityId: 'mumbai', name: 'Santacruz West', pincode: '400054' },

  // Bengaluru (Koramangala domain area hub)
  { id: 'koramangala-4', cityId: 'bengaluru', name: 'Koramangala 4th Block', pincode: '560034' },
  { id: 'koramangala-5', cityId: 'bengaluru', name: 'Koramangala 5th Block', pincode: '560095' },
  { id: 'indiranagar', cityId: 'bengaluru', name: 'Indiranagar', pincode: '560038' },
  { id: 'hsr-layout', cityId: 'bengaluru', name: 'HSR Layout', pincode: '560102' },

  // New Delhi (Connaught Place domain area hub)
  { id: 'cp-inner', cityId: 'delhi', name: 'Connaught Place Inner Circle', pincode: '110001' },
  { id: 'cp-outer', cityId: 'delhi', name: 'Connaught Place Outer Circle', pincode: '110001' },
  { id: 'karol-bagh', cityId: 'delhi', name: 'Karol Bagh', pincode: '110005' },
  { id: 'saket', cityId: 'delhi', name: 'Saket', pincode: '110017' }
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'all', name: 'All Categories', icon: 'Grid', color: 'bg-emerald-500/10 text-emerald-600' },
  { id: 'food', name: 'Food & Dining', icon: 'Utensils', color: 'bg-amber-500/10 text-amber-600' },
  { id: 'tech', name: 'Tech & Digital', icon: 'Laptop', color: 'bg-blue-500/10 text-blue-600' },
  { id: 'health', name: 'Health & Medical', icon: 'HeartPulse', color: 'bg-rose-500/10 text-rose-600' },
  { id: 'home', name: 'Home Services', icon: 'Wrench', color: 'bg-orange-500/10 text-orange-600' },
  { id: 'services', name: 'Professional Services', icon: 'Briefcase', color: 'bg-purple-500/10 text-purple-600' },
  { id: 'retail', name: 'Shops & Retail', icon: 'ShoppingBag', color: 'bg-pink-500/10 text-pink-600' },
];

export const INITIAL_LOCALITIES: Locality[] = [
  {
    id: 'bandra',
    name: 'Bandra West, Mumbai',
    slug: 'bandra',
    subdomain: 'bandra.yellowpages.co.in',
    description: 'Explore trendy sea-facing cafes, premium fashion designer boutiques, and local services across the Queen of Suburbs.',
    status: 'active',
    coverImage: 'https://images.unsplash.com/photo-1570168007244-23704139443d?auto=format&fit=crop&w=600&q=80',
    stats: { numBusinesses: 3, numPending: 2 },
    carouselImages: [
      'https://images.unsplash.com/photo-1570168007244-23704139443d?auto=format&fit=crop&w=800&q=80', // Bandra Worli Sea Link 1
      'https://images.unsplash.com/photo-1566552881560-0be862a7c445?auto=format&fit=crop&w=800&q=80', // Mumbai taxi / streets 2
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80'  // Coffee / Cafe view 3
    ]
  },
  {
    id: 'koramangala',
    name: 'Koramangala, Bengaluru',
    slug: 'koramangala',
    subdomain: 'koramangala.yellowpages.co.in',
    description: 'Uncover premier tech startups, venture capitals, artisanal bakeries, and high-quality consulting agencies in Silicon Valley.',
    status: 'active',
    coverImage: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=600&q=80',
    stats: { numBusinesses: 2, numPending: 1 },
    carouselImages: [
      'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80', // Bengaluru office building
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80', // Cafe workspace
      'https://images.unsplash.com/photo-1590579491410-062e240b2f81?auto=format&fit=crop&w=800&q=80'  // Green avenues
    ]
  },
  {
    id: 'cp',
    name: 'Connaught Place, New Delhi',
    slug: 'cp',
    subdomain: 'cp.yellowpages.co.in',
    description: 'Find historic colonnade retail showrooms, elite legal chambers, and celebrated legacy dining outlets in New Delhi.',
    status: 'active',
    coverImage: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=600&q=80',
    stats: { numBusinesses: 2, numPending: 0 },
    carouselImages: [
      'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80', // CP Delhi Heritage white pillars
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&q=80', // Tech office Delhi
      'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80'  // Old monument
    ]
  }
];

// Seed initial authentic reviews and businesses with discovery and monetization fields.
export const INITIAL_BUSINESSES: Business[] = [
  // Bandra Approved
  {
    id: 'b1',
    name: 'The Bandra Seaside Bistro',
    categoryId: 'food',
    localityId: 'bandra',
    stateId: 'mh',
    cityId: 'mumbai',
    areaId: 'bandra-w',
    areasOfOperation: ['bandra-w', 'khar-w', 'juhu'],
    address: 'Plot 42, Carter Rd, Bandra West, Mumbai, MH 400050',
    phone: '+91 22 5550 9012',
    email: 'hello@bandraseasidebistro.in',
    website: 'https://bandraseasidebistro.in',
    description: 'Award-winning sea-facing diner specializing in artisanal seafood platters, progressive continental desserts, and organic cold brews.',
    rating: 4.8,
    reviewCount: 4,
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=500&q=80',
    featured: true,
    status: 'approved',
    createdAt: '2026-01-20T11:00:00Z',
    tags: ['Cafe', 'Seaside', 'Seafood', 'Bistro'],
    hours: '11:00 AM - 11:30 PM',
    ownerName: 'Rahul Merchant',
    gpsCoordinates: { lat: 19.0601, lng: 72.8229 },
    distance: 0.8,
    priceRange: '₹₹₹',
    deliveryAvailable: true,
    hasOffers: true,
    languagesSpoken: ['English', 'Hindi', 'Marathi'],
    paymentMethods: ['UPI', 'Card', 'Cash'],
    experienceYears: 8,
    isSponsored: true,
    cpcBudget: 350,
    verifiedBadge: true,
    kycStatus: 'verified',
    govRegistered: true,
    responseTime: '< 10 mins',
    customerSatisfaction: 96,
    repeatCustomerScore: 84,
    isMonthlySubscriber: true,
    subscriptionPlan: 'premium'
  },
  {
    id: 'b2',
    name: 'Aura Premium Dental Clinic',
    categoryId: 'health',
    localityId: 'bandra',
    stateId: 'mh',
    cityId: 'mumbai',
    areaId: 'bandra-w',
    areasOfOperation: ['bandra-w', 'khar-w', 'santacruz-w'],
    address: 'Shop 5, Pali Hill Heights, Bandra West, Mumbai, MH 400050',
    phone: '+91 22 5550 4322',
    email: 'smile@auradental.in',
    website: 'https://auradental.in',
    description: 'Bespoke dental aesthetic restorations, painless root canal surgeries, and advanced biological teeth alignments with transparent braces.',
    rating: 4.9,
    reviewCount: 3,
    imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=500&q=80',
    featured: true,
    status: 'approved',
    createdAt: '2026-02-15T09:30:00Z',
    tags: ['Dentist', 'Orthodontist', 'Smile Design'],
    hours: '10:00 AM - 08:00 PM',
    ownerName: 'Dr. Ananya Sharma',
    gpsCoordinates: { lat: 19.0620, lng: 72.8258 },
    distance: 1.2,
    priceRange: '₹₹₹₹',
    deliveryAvailable: false,
    hasOffers: false,
    languagesSpoken: ['English', 'Hindi', 'Gujarati'],
    paymentMethods: ['Card', 'UPI'],
    experienceYears: 12,
    isSponsored: false,
    cpcBudget: 100,
    verifiedBadge: true,
    kycStatus: 'verified',
    govRegistered: true,
    responseTime: '< 30 mins',
    customerSatisfaction: 98,
    repeatCustomerScore: 91,
    isMonthlySubscriber: true,
    subscriptionPlan: 'basic'
  },
  {
    id: 'b3',
    name: 'Hill Road Heritage Handlooms',
    categoryId: 'retail',
    localityId: 'bandra',
    stateId: 'mh',
    cityId: 'mumbai',
    areaId: 'bandra-w',
    areasOfOperation: ['bandra-w', 'bandra-e', 'khar-w'],
    address: 'Hill Road, Near Bandra Station, Mumbai, MH 400050',
    phone: '+91 22 5550 1198',
    email: 'contact@heritagehandlooms.in',
    website: 'https://heritagehandlooms.in',
    description: 'Authentic Indian ethnic handloom sarees, bespoke linen kurtas, and handcrafted sustainable leather accessories sourced from rural weavers.',
    rating: 4.5,
    reviewCount: 1,
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=500&q=80',
    featured: false,
    status: 'approved',
    createdAt: '2026-03-01T10:00:00Z',
    tags: ['Ethnic Wear', 'Handloom', 'Saree', 'Fashion'],
    hours: '10:30 AM - 09:00 PM',
    ownerName: 'Surendra Gupta',
    gpsCoordinates: { lat: 19.0573, lng: 72.8341 },
    distance: 2.4,
    priceRange: '₹₹',
    deliveryAvailable: true,
    hasOffers: true,
    languagesSpoken: ['Hindi', 'Marathi', 'English'],
    paymentMethods: ['Cash', 'UPI', 'Card'],
    experienceYears: 15,
    isSponsored: false,
    cpcBudget: 50,
    verifiedBadge: true,
    kycStatus: 'pending',
    govRegistered: true,
    responseTime: '< 1 hour',
    customerSatisfaction: 92,
    repeatCustomerScore: 78,
    isMonthlySubscriber: false,
    subscriptionPlan: 'free'
  },

  // Koramangala Approved
  {
    id: 'b4',
    name: 'Koramangala TechCraft Labs',
    categoryId: 'tech',
    localityId: 'koramangala',
    stateId: 'ka',
    cityId: 'bengaluru',
    areaId: 'koramangala-4',
    areasOfOperation: ['koramangala-4', 'koramangala-5', 'hsr-layout'],
    address: '810, 80 Feet Road, 4th Block, Koramangala, Bengaluru, KA 560034',
    phone: '+91 80 5558 1234',
    email: 'services@techcraftlabs.io',
    website: 'https://techcraftlabs.io',
    description: 'Agile custom React development, serverless node API architectures, devops cloud migrations, and product design consultants.',
    rating: 5.0,
    reviewCount: 1,
    imageUrl: 'https://images.unsplash.com/photo-1600132806370-bf17e65e942f?auto=format&fit=crop&w=500&q=80',
    featured: true,
    status: 'approved',
    createdAt: '2026-04-10T09:00:00Z',
    tags: ['SaaS Development', 'Cloud Devops', 'React', 'Mobile Apps'],
    hours: '09:00 AM - 06:30 PM',
    ownerName: 'Vikram Sundaram',
    gpsCoordinates: { lat: 12.9343, lng: 77.6244 },
    distance: 0.5,
    priceRange: '₹₹₹',
    deliveryAvailable: false,
    hasOffers: false,
    languagesSpoken: ['English', 'Kannada', 'Hindi', 'Tamil'],
    paymentMethods: ['Card', 'UPI'],
    experienceYears: 6,
    isSponsored: true,
    cpcBudget: 400,
    verifiedBadge: true,
    kycStatus: 'verified',
    govRegistered: true,
    responseTime: '< 15 mins',
    customerSatisfaction: 99,
    repeatCustomerScore: 89,
    isMonthlySubscriber: true,
    subscriptionPlan: 'premium'
  },
  {
    id: 'b5',
    name: 'Sardar Filter Coffee & Tiffin House',
    categoryId: 'food',
    localityId: 'koramangala',
    stateId: 'ka',
    cityId: 'bengaluru',
    areaId: 'koramangala-5',
    areasOfOperation: ['koramangala-5', 'hsr-layout', 'indiranagar'],
    address: '12, 100 Feet Road, 5th Block, Koramangala, Bengaluru, KA 560034',
    phone: '+91 80 5558 7788',
    email: undefined,
    website: 'https://sardarcoffee.in',
    description: 'Crispy ghee podi idlis, authentic wood-fired rava dosa plates, and aromatic grade cup chicory-filter coffee served in traditional brass cups.',
    rating: 4.8,
    reviewCount: 2,
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=500&q=80',
    featured: false,
    status: 'approved',
    createdAt: '2026-03-24T07:00:00Z',
    tags: ['Filter Coffee', 'South Indian', 'Breakfast', 'Dosa'],
    hours: '06:30 AM - 10:00 PM',
    ownerName: 'Kamesh Iyer',
    gpsCoordinates: { lat: 12.9317, lng: 77.6225 },
    distance: 1.5,
    priceRange: '₹',
    deliveryAvailable: true,
    hasOffers: true,
    languagesSpoken: ['Kannada', 'Tamil', 'English', 'Hindi'],
    paymentMethods: ['Cash', 'UPI'],
    experienceYears: 25,
    isSponsored: false,
    cpcBudget: 0,
    verifiedBadge: true,
    kycStatus: 'verified',
    govRegistered: true,
    responseTime: '< 5 mins',
    customerSatisfaction: 97,
    repeatCustomerScore: 95,
    isMonthlySubscriber: false,
    subscriptionPlan: 'free'
  },

  // CP Approved
  {
    id: 'b6',
    name: 'Nirmaan Legal Alliance',
    categoryId: 'services',
    localityId: 'cp',
    stateId: 'dl',
    cityId: 'delhi',
    areaId: 'cp-inner',
    areasOfOperation: ['cp-inner', 'cp-outer', 'saket'],
    address: 'F-24, Inner Circle, Connaught Place, New Delhi, DL 110001',
    phone: '+91 11 5557 9002',
    email: 'advice@nirmaanlaw.in',
    website: 'https://nirmaanlaw.in',
    description: 'Supreme Court corporate law litigators, intellectual property trademark filings, estate succession structuring, and legal compliance.',
    rating: 4.9,
    reviewCount: 3,
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=500&q=80',
    featured: true,
    status: 'approved',
    createdAt: '2026-04-18T10:00:00Z',
    tags: ['Lawyers', 'Supreme Court', 'IP Patent', 'Corporate Law'],
    hours: '09:30 AM - 07:00 PM',
    ownerName: 'Devashish Sen, Adv.',
    gpsCoordinates: { lat: 28.6304, lng: 77.2177 },
    distance: 0.4,
    priceRange: '₹₹₹₹',
    deliveryAvailable: false,
    hasOffers: false,
    languagesSpoken: ['English', 'Hindi'],
    paymentMethods: ['Card', 'UPI'],
    experienceYears: 18,
    isSponsored: false,
    cpcBudget: 150,
    verifiedBadge: true,
    kycStatus: 'verified',
    govRegistered: true,
    responseTime: '< 2 hours',
    customerSatisfaction: 95,
    repeatCustomerScore: 82,
    isMonthlySubscriber: true,
    subscriptionPlan: 'basic'
  },
  {
    id: 'b7',
    name: 'Delhi Powergrid Electrics',
    categoryId: 'home',
    localityId: 'cp',
    stateId: 'dl',
    cityId: 'delhi',
    areaId: 'cp-outer',
    areasOfOperation: ['cp-outer', 'karol-bagh'],
    address: 'Block H, Outer Circle, Connaught Place, New Delhi, DL 110001',
    phone: '+91 11 5557 2322',
    email: undefined,
    website: 'https://delhipowergrid.in',
    description: '24/7 commercial power backup solutions, automatic stabilizer calibrations, and fast response residential appliance wiring diagnostics.',
    rating: 4.6,
    reviewCount: 1,
    imageUrl: 'https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?auto=format&fit=crop&w=500&q=80',
    featured: false,
    status: 'approved',
    createdAt: '2026-01-15T08:00:00Z',
    tags: ['Electrician', 'Inverter Repair', 'Emergency Plugs'],
    hours: '24 Hours Emergency Help',
    ownerName: 'Manbir Grewal',
    gpsCoordinates: { lat: 28.6295, lng: 77.2198 },
    distance: 2.1,
    priceRange: '₹₹',
    deliveryAvailable: true,
    hasOffers: false,
    languagesSpoken: ['Hindi', 'Punjabi', 'English'],
    paymentMethods: ['Cash', 'UPI'],
    experienceYears: 9,
    isSponsored: false,
    cpcBudget: 200,
    verifiedBadge: true,
    kycStatus: 'verified',
    govRegistered: true,
    responseTime: '< 20 mins',
    customerSatisfaction: 94,
    repeatCustomerScore: 86,
    isMonthlySubscriber: false,
    subscriptionPlan: 'free'
  },

  // PENDING Indian store applicants
  {
    id: 'b8',
    name: 'Bandra Organic Wellness Store',
    categoryId: 'health',
    localityId: 'bandra',
    stateId: 'mh',
    cityId: 'mumbai',
    areaId: 'bandra-w',
    areasOfOperation: ['bandra-w', 'khar-w'],
    address: 'Shop 12, Shirley Rajan Rd, Bandra West, Mumbai, MH 400050',
    phone: '+91 22 5550 8821',
    email: 'info@bandraorganics.in',
    website: 'https://bandraorganics.in',
    description: 'Fresh cold-pressed natural seed oils, pure forest honey, standard pesticide-free farm millets, and chemical-free wellness skincare.',
    rating: 0.0,
    reviewCount: 0,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=500&q=80',
    featured: false,
    status: 'pending',
    createdAt: '2026-05-18T05:00:00Z',
    tags: ['Organic Food', 'Cold-pressed', 'Honey', 'Wellness'],
    hours: '09:00 AM - 09:00 PM',
    ownerName: 'Radhika Vasudev',
    gpsCoordinates: { lat: 19.0551, lng: 72.8288 },
    distance: 1.8,
    priceRange: '₹₹',
    deliveryAvailable: true,
    hasOffers: true,
    languagesSpoken: ['Hindi', 'English', 'Marathi'],
    paymentMethods: ['UPI', 'Cash'],
    experienceYears: 4,
    isSponsored: false,
    cpcBudget: 0,
    verifiedBadge: false,
    kycStatus: 'pending',
    govRegistered: false,
    responseTime: '< 15 mins',
    customerSatisfaction: 0,
    repeatCustomerScore: 0,
    isMonthlySubscriber: false,
    subscriptionPlan: 'free'
  },
  {
    id: 'b9',
    name: 'Mumbai Marine Smart Guard',
    categoryId: 'home',
    localityId: 'bandra',
    stateId: 'mh',
    cityId: 'mumbai',
    areaId: 'juhu',
    areasOfOperation: ['juhu', 'bandra-w', 'khar-w'],
    address: 'St Andrews Road, Bandra West, Mumbai, MH 400050',
    phone: '+91 22 5550 7701',
    website: 'https://mumbaismartguard.in',
    description: 'Advanced biometric smart latch lock integrations, thermal fire alarms, and secure surveillance camera hub setups.',
    rating: 0.0,
    reviewCount: 0,
    imageUrl: 'https://images.unsplash.com/photo-1558223140-50fa89b0b695?auto=format&fit=crop&w=500&q=80',
    featured: false,
    status: 'pending',
    createdAt: '2026-05-19T14:30:00Z',
    tags: ['Smart locks', 'Locksmith', 'CCTV Security'],
    hours: '24/7 Security Audits',
    ownerName: 'Prasoon Abraham',
    gpsCoordinates: { lat: 19.0523, lng: 72.8290 },
    distance: 1.4,
    priceRange: '₹₹₹',
    deliveryAvailable: true,
    hasOffers: false,
    languagesSpoken: ['English', 'Hindi', 'Malayalam'],
    paymentMethods: ['UPI', 'Card', 'Cash'],
    experienceYears: 5,
    isSponsored: false,
    cpcBudget: 0,
    verifiedBadge: false,
    kycStatus: 'none',
    govRegistered: true,
    responseTime: '< 45 mins',
    customerSatisfaction: 0,
    repeatCustomerScore: 0,
    isMonthlySubscriber: false,
    subscriptionPlan: 'free'
  },
  {
    id: 'b10',
    name: 'Koramangala Serverless Stack',
    categoryId: 'tech',
    localityId: 'koramangala',
    stateId: 'ka',
    cityId: 'bengaluru',
    areaId: 'koramangala-4',
    areasOfOperation: ['koramangala-4', 'koramangala-5'],
    address: 'Startup Enclave, Outer Ring Rd, Koramangala, Bengaluru, KA 560034',
    phone: '+91 80 5558 9911',
    email: 'hello@serverlessstack.in',
    website: 'https://serverlessstack.in',
    description: 'Scale-to-zero serverless backends deploying on AWS lambda and GCP cloud runs. Automated cost reduction audits.',
    rating: 0.0,
    reviewCount: 0,
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=500&q=80',
    featured: false,
    status: 'pending',
    createdAt: '2026-05-20T06:00:00Z',
    tags: ['AWS Lambda', 'Cloud Costs', 'Kubernetes'],
    hours: '09:00 AM - 06:00 PM',
    ownerName: 'Aditya Hegde',
    gpsCoordinates: { lat: 12.9341, lng: 77.6250 },
    distance: 2.8,
    priceRange: '₹₹₹',
    deliveryAvailable: false,
    hasOffers: false,
    languagesSpoken: ['English', 'Kannada'],
    paymentMethods: ['UPI'],
    experienceYears: 7,
    isSponsored: false,
    cpcBudget: 0,
    verifiedBadge: false,
    kycStatus: 'none',
    govRegistered: false,
    responseTime: '< 30 mins',
    customerSatisfaction: 0,
    repeatCustomerScore: 0,
    isMonthlySubscriber: false,
    subscriptionPlan: 'free'
  }
];

// Seed initial authentic reviews
export const INITIAL_REVIEWS = [
  {
    id: 'r1',
    businessId: 'b1',
    userName: 'Karan Malhotra',
    userPhone: '+918001122334',
    rating: 5,
    comment: 'Exceptional continental desserts and the sea link vista breeze is unmatched on a warm Bandra sunset. Truly lovely!',
    createdAt: '2026-04-12T14:00:00Z',
    verifiedByOtp: true,
    photoUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=300&q=80',
    isVerifiedPurchase: true,
    helpfulVotes: 12
  },
  {
    id: 'r2',
    businessId: 'b1',
    userName: 'Sunita Rao',
    userPhone: '+919911223344',
    rating: 4,
    comment: 'The seafood was perfectly cooked. Docking one star because parking on Carters Road is absolute chaos. Highly recommend taking an auto!',
    createdAt: '2026-05-01T08:15:00Z',
    verifiedByOtp: true,
    isVerifiedPurchase: true,
    helpfulVotes: 4
  },
  {
    id: 'r3',
    businessId: 'b2',
    userName: 'Akshay Kumar',
    userPhone: '+919876543210',
    rating: 5,
    comment: 'Most hygienic and professional biological dentist in Pali Hill. Dr. Ananya explains the root canal process meticulously.',
    createdAt: '2026-03-20T10:30:00Z',
    verifiedByOtp: true,
    photoUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=300&q=80',
    isVerifiedPurchase: false,
    helpfulVotes: 9
  }
];

export const INITIAL_COMMUNITY_ITEMS: CommunityItem[] = [
  {
    id: 'c1',
    type: 'qa',
    title: 'Any pure veg authentic South Indian lunch around Bandra West?',
    content: 'Looking for standard banana-leaf lunch options that open early and provide quick hot filter coffees. Any recommendations, friends?',
    authorName: 'Ramesh Mehta',
    authorPhone: '+91 98888 77777',
    createdAt: '2026-05-18T10:00:00Z',
    localityId: 'bandra',
    likes: 8,
    answersCount: 2,
    answers: [
      { id: 'ca1', authorName: 'Suresh Kumar', content: 'You can check Hill Road for small traditional mess halls, but most premium high-quality tiffins are in Crawford Market or Sion.', createdAt: '2026-05-18T11:30:00Z' },
      { id: 'ca2', authorName: 'Amruta Fadnis', content: 'Hill Road Heritage Handlooms owner highly recommended a small South Indian cafe near the west exit of the railway terminal!', createdAt: '2026-05-18T12:00:00Z' }
    ]
  },
  {
    id: 'c2',
    type: 'deal',
    title: 'Monsoon Special: Flat 15% discount on Bistro continental platters!',
    content: 'Get flat 15% discount on all fish baskets and sea-facing dinner tables this Friday. Verify your phone on YellowPages to claim!',
    authorName: 'Rahul Merchant (Proprietor)',
    createdAt: '2026-05-19T06:00:00Z',
    businessId: 'b1',
    localityId: 'bandra',
    likes: 15,
    dealPromoCode: 'BISTROMONSOON15',
    isSponsored: true
  },
  {
    id: 'c3',
    type: 'event',
    title: 'Koramangala React Engineers and SaaS Founders Meetup',
    content: 'Annual regional code coffee sharing & MVP showcase at TechCraft Labs workshop lobby. Attendance is free but RSVP required.',
    authorName: 'Vikram Sundaram (VP TechCraft)',
    createdAt: '2026-05-19T14:00:00Z',
    businessId: 'b4',
    localityId: 'koramangala',
    likes: 21,
    eventDate: '2026-05-24 • 10:00 AM'
  },
  {
    id: 'c4',
    type: 'recommendation',
    title: 'Honest review: Painless scaling done at Aura Premium Dental Clinic',
    content: 'Had a terrible wisdom tooth pain last Sunday. Dr. Ananya was exceptionally composed and completed the biological alignment without pain. Highly recommended for people with clinic anxiety.',
    authorName: 'Kartik Aaryan',
    createdAt: '2026-05-17T08:30:00Z',
    businessId: 'b2',
    localityId: 'bandra',
    likes: 19
  }
];

export const INITIAL_CRM_CONTACTS: CRMContact[] = [
  {
    id: 'crm1',
    businessId: 'b5',
    name: 'Anish Bhat',
    phone: '+91 98311 00223',
    email: 'anish@startuphub.io',
    lastInteraction: '2026-05-19T08:00:00Z',
    followUpNotes: 'Regular coffee drinker. Orders 10 filter coffees every Monday morning.',
    totalSpent: 4200,
    ordersCount: 15,
    loyaltyPoints: 420
  },
  {
    id: 'crm2',
    businessId: 'b5',
    name: 'Meera Deshpande',
    phone: '+91 88912 33441',
    email: 'meera.dp@gmail.com',
    lastInteraction: '2026-05-18T16:30:00Z',
    followUpNotes: 'Inquired about catering 50 plates of podi mini idlis for housing board meet.',
    totalSpent: 1200,
    ordersCount: 4,
    loyaltyPoints: 120
  },
  {
    id: 'crm3',
    businessId: 'b1',
    name: 'Karan Malhotra',
    phone: '+91 80011 22334',
    email: 'karan@bistroloyer.in',
    lastInteraction: '2026-05-20T08:15:00Z',
    followUpNotes: 'Excellent customer. Sent thank-you coupon for his 5-star continental review.',
    totalSpent: 8500,
    ordersCount: 8,
    loyaltyPoints: 850
  }
];

export const INITIAL_COUPONS: MarketingCoupon[] = [
  {
    id: 'cpn1',
    businessId: 'b5',
    code: 'SARDAR50',
    discount: '₹50 Off',
    description: 'Get Flat ₹50 Off on orders above ₹200. Valid on tiffin items.',
    expiryDate: '2026-06-30',
    usageCount: 42
  },
  {
    id: 'cpn2',
    businessId: 'b1',
    code: 'BISTRO15',
    discount: '15% Off',
    description: 'Flat 15% discount on all premium seafood and dine-in tables.',
    expiryDate: '2026-06-15',
    usageCount: 19
  },
  {
    id: 'cpn3',
    businessId: 'b2',
    code: 'AURASMILE',
    discount: '₹500 Off',
    description: 'Get ₹500 off on professional laser orthodontic cleaning.',
    expiryDate: '2026-07-31',
    usageCount: 7
  }
];
